# =============================================================================
# TensorCore-FPGA - PYNQ-Z1 Constraints for PS-Integrated Design
# Target Board: PYNQ-Z1 (Digilent/TUL)
# FPGA: Zynq-7020 (XC7Z020-1CLG400C)
# =============================================================================
# This XDC file is for PS-integrated block design where clock comes from
# the Zynq Processing System FCLK_CLK0 (100 MHz).
# =============================================================================

# =============================================================================
# CLOCK - Comes from PS (FCLK_CLK0)
# =============================================================================
# No need to create clock here - it's generated by PS block
# The PS FCLK_CLK0 is automatically constrained by Vivado

# =============================================================================
# LED OUTPUTS
# =============================================================================
# LED0 - Done indicator
set_property -dict { PACKAGE_PIN R14   IOSTANDARD LVCMOS33 } [get_ports { led_done }]

# LED1 - Busy indicator
set_property -dict { PACKAGE_PIN P14   IOSTANDARD LVCMOS33 } [get_ports { led_busy }]

# LED2-3 - State indicators
set_property -dict { PACKAGE_PIN N16   IOSTANDARD LVCMOS33 } [get_ports { led_state[0] }]
set_property -dict { PACKAGE_PIN M14   IOSTANDARD LVCMOS33 } [get_ports { led_state[1] }]

# =============================================================================
# OPTIONAL DEBUG BUTTONS (directly from board)
# =============================================================================
# BTN0 - Can be used as manual reset (directly to board, active high)
# set_property -dict { PACKAGE_PIN D19   IOSTANDARD LVCMOS33 } [get_ports { btn_reset }]

# BTN1 - Can be used as manual start trigger
# set_property -dict { PACKAGE_PIN D20   IOSTANDARD LVCMOS33 } [get_ports { btn_start }]

# =============================================================================
# RGB LEDs (optional for status indication)
# =============================================================================
# RGB LED 4 
# set_property -dict { PACKAGE_PIN L15   IOSTANDARD LVCMOS33 } [get_ports { led4_b }]
# set_property -dict { PACKAGE_PIN G17   IOSTANDARD LVCMOS33 } [get_ports { led4_g }]
# set_property -dict { PACKAGE_PIN N15   IOSTANDARD LVCMOS33 } [get_ports { led4_r }]

# =============================================================================
# TIMING CONSTRAINTS
# =============================================================================
# LED outputs are relaxed - no strict timing required
set_output_delay -clock [get_clocks clk_fpga_0] -max 5.0 [get_ports { led_* }]
set_output_delay -clock [get_clocks clk_fpga_0] -min 0.0 [get_ports { led_* }]

# Set false path to LED outputs (they're slow indicators only)
set_false_path -to [get_ports { led_* }]

# =============================================================================
# CONFIGURATION OPTIONS
# =============================================================================
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

# =============================================================================
# BITSTREAM OPTIONS
# =============================================================================
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLUP [current_design]
